apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettoolbox
  labels:
    app: nettoolbox
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nettoolbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nettoolbox
    spec:
      containers:
      - command:
        - sleep 9999
        image: isstech/nettoolbox:0.1
        imagePullPolicy: Always
        name: nettoolbox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
